apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ291c2Vy
  MONGO_INITDB_ROOT_PASSWORD: c2VjdXJlcGFzcw==
  ME_CONFIG_MONGODB_ADMINUSERNAME: bW9uZ291c2Vy
  ME_CONFIG_MONGODB_ADMINPASSWORD: c2VjdXJlcGFzcw==